{
 "title": "Antelope Nodeos Extended 5.0 (Public)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "NodeOS 5.0 (Beta)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EOS Transfers CPU Usage",
   "type": "timeseries",
   "description": "EOS Transfers CPU Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "{{producer}}" }
   ]
  },
  {
   "title": "P2P Failed Connections on 1h",
   "type": "timeseries",
   "description": "Number of failed p2p connections (Incremental counter) using delta",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_failed_connections[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total CPU usage for blocks on 1h",
   "type": "timeseries",
   "description": "Total number of CPU Usage in microseconds for incoming/outgoing blocks using delta",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_cpu_usage_us_total[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{block_type}}"
    }
   ]
  },
  {
   "title": "Total NET usage for blocks on 1h",
   "type": "timeseries",
   "description": "Total number of NET Usage in microseconds for incoming/outgoing blocks using delta",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_net_usage_us_total[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{block_type}}"
    }
   ]
  },
  {
   "title": "Total Unapplied Transactions from Produced Blocks on 1h",
   "type": "timeseries",
   "description": "Total number of unapplied transactions from produced blocks using delta\n\nThis is the current number of transactions in the unapplied transaction queue. The unapplied transaction queue is the queue of transactions that have been aborted out of a speculative block (or forked block). Also includes trxs that have entered the node when it is not producing a block.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_unapplied_transactions_total[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total subjective billed accounts from produced blocks on 1h",
   "type": "timeseries",
   "description": "This is the current number of accounts that have local subjective billing.\n\nIt is the first authorizer account of a trx that has any subjective billing. It has submitted a trx that failed or has not yet been included in a block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_subjective_bill_account_size_total[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total number of transactions produced on 1h",
   "type": "timeseries",
   "description": "Total number of transactions produced in a block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_trxs_produced_total[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total produced blocks elapsed time on 1h",
   "type": "timeseries",
   "description": "Total produced blocks elapsed time (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_produced_elapsed_us_total[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total time of produced blocks on 1h",
   "type": "timeseries",
   "description": "Total time of produced blocks (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_produced_us_total[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of blocks produced on 1h",
   "type": "timeseries",
   "description": "Number of blocks produced (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_blocks_produced[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total time for produced block on 1h",
   "type": "timeseries",
   "description": "Total time for produced block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_total_time_us_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Idle time for produced block on 1h",
   "type": "timeseries",
   "description": "Idle time for produced block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_idle_time_us_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of successful transactions in produced block on 1h",
   "type": "timeseries",
   "description": "Number of successful transactions in produced block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_num_success_trx_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Time for successful transactions in produced block on 1h",
   "type": "timeseries",
   "description": "Time for successful transactions in produced block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_success_trx_time_us_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of failed transactions in produced block on 1h",
   "type": "timeseries",
   "description": "Number of failed transactions in produced block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_num_failed_trx_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Time for failed transactions in produced block on 1h",
   "type": "timeseries",
   "description": "Time for failed transactions in produced block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_fail_trx_time_us_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of transient transactions in produced block on 1h",
   "type": "timeseries",
   "description": "Number of transient transactions in produced block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_num_transient_trx_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Time for transient transactions in produced block on 1h",
   "type": "timeseries",
   "description": "Time for transient transactions in produced block (BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_transient_trx_time_us_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Other unaccounted time during produced block on 1h",
   "type": "timeseries",
   "description": "Other unaccounted time during produced block(BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_other_time_us_produced_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of speculative blocks created on 1h",
   "type": "timeseries",
   "description": "Number of speculative blocks created",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_blocks_speculative_num[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total time for speculative blocks on 1h",
   "type": "timeseries",
   "description": "Total time for speculative blocks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_total_time_us_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Idle time for speculative blocks on 1h",
   "type": "timeseries",
   "description": "Idle time for speculative blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_idle_time_us_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of successful transactions in speculative block on 1h",
   "type": "timeseries",
   "description": "Number of successful transactions in speculative block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_num_success_trx_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Time for successful transactions in speculative block on 1h",
   "type": "timeseries",
   "description": "Time for successful transactions in speculative block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_success_trx_time_us_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of failed transactions in speculative block on 1h",
   "type": "timeseries",
   "description": "Number of failed transactions in speculative block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_num_failed_trx_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Time for failed transactions in speculative block on 1h",
   "type": "timeseries",
   "description": "Time for failed transactions in speculative block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_fail_trx_time_us_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of transient transactions in speculative block on 1h",
   "type": "timeseries",
   "description": "Number of transient transactions in speculative block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_num_transient_trx_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Time for transient transactions in speculative block on 1h",
   "type": "timeseries",
   "description": "Time for transient transactions in speculative block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_transient_trx_time_us_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Other unaccounted time during speculative block on 1h",
   "type": "timeseries",
   "description": "Other unaccounted time during speculative block(BP only)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_other_time_us_speculative_block[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total number of incoming transactions on 1h",
   "type": "timeseries",
   "description": "Total number of incoming transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_trxs_incoming_total[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total incoming blocks elapsed time on 1h",
   "type": "timeseries",
   "description": "Total incoming blocks elapsed time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_incoming_elapsed_us_total[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Total incoming block latency on 1h",
   "type": "timeseries",
   "description": "Total incoming block latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(nodeos_incoming_us_block_latency[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of incoming blocks on 1h",
   "type": "timeseries",
   "description": "Number of incoming blocks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_blocks_incoming[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Number of connected outgoing peers on 1h",
   "type": "timeseries",
   "description": "Number of connected outgoing peers P2P",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "increase(nodeos_p2p_peers[1h])", "legendFormat": "{{network}} - {{hostname}}" }
   ]
  },
  {
   "title": "Number of connected incoming peers on 1h",
   "type": "timeseries",
   "description": "Number of connected incoming peers P2P",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_clients[1h])",
     "legendFormat": "{{network}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "P2P Peers on 1h",
   "type": "timeseries",
   "description": "P2P Peers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_addr[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Last Received Blocks",
   "type": "timeseries",
   "description": "P2P Last Received Blocks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodeos_p2p_last_received_block",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P First Available Blocks",
   "type": "timeseries",
   "description": "P2P First Available Blocks\n\n“0” here means unknown. Only 5.0+ nodeos reports this info to peers. So the peer has to be 5.0+ for this to not be 0.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodeos_p2p_first_available_block",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Last Available Blocks",
   "type": "timeseries",
   "description": "P2P Last Available Blocks\n\nif a peer node is syncing and not at current block this might be less than current block number.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodeos_p2p_last_available_block",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Unique First Block count on 1h",
   "type": "timeseries",
   "description": "P2P Unique First Block count\n\nWhen receiving blocks from the network, this tells you which connection is sending you the most blocks first/it is a really good peer. Peers where you get no new blocks might be less important. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_unique_first_block_count[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Latency on 1h",
   "type": "timeseries",
   "description": "P2P Latency ping in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_latency[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Total bytes received on 1h",
   "type": "timeseries",
   "description": "P2P Total bytes received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_bytes_received[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Last bytes received on 1h",
   "type": "timeseries",
   "description": "P2P Last bytes received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_last_bytes_received[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Total bytes sent on 1h",
   "type": "timeseries",
   "description": "P2P Total bytes sent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_bytes_sent[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Last bytes sent on 1h",
   "type": "timeseries",
   "description": "P2P Last bytes sent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_last_bytes_sent[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "Bytes of blocks received during syncing on 1h",
   "type": "timeseries",
   "description": "Bytes of blocks received during syncing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_block_sync_bytes_received[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "Bytes of blocks sent during syncing on 1h",
   "type": "timeseries",
   "description": "Bytes of blocks sent during syncing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nodeos_p2p_block_sync_bytes_sent[1h])",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "Is block sync throttling currently active",
   "type": "timeseries",
   "description": "Is block sync throttling currently active (Boolean)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "nodeos_p2p_block_sync_throttling",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  },
  {
   "title": "P2P Connection Start Time",
   "type": "timeseries",
   "description": "P2P Connection Start Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "targets": [
    {
     "expr": "nodeos_p2p_connection_start_time / 1000000",
     "legendFormat": "{{network}} - {{hostname}} - {{connid}}"
    }
   ]
  }
 ]
}